#!/bin/bash
CURRENT=$(date +%s)
INPUT=$(date -d $1 +%s)
INPUT_MSG=$2
[[ -z $2 ]] && INPUT_MSG="Alarm!"

RESULT=$(($INPUT - $CURRENT))
RESULT_MIN=$(($RESULT / 60))
RESULT_SEC=$(($RESULT % 60))

echo "Alarm will ring after $RESULT_MIN minuite(s) and $RESULT_SEC second(s)."
sleep $RESULT && ~/chaeriapps/notify $INPUT_MSG $3 &
