#!/bin/bash
VAL=$1
REPEAT=$2
if [ -z $1 ]
    then VAL=BEL!
fi
echo $VAL

if [[ "$REPEAT" -eq 0 ]]
    then 
    REPEAT=3  
fi

i=1
while [ $i -le $REPEAT ]
do
    tput bel
    sleep 1
    ((i++))
done
